In [25]:
import pandas as pd
import numpy as np
import hashlib


print("Pandas: ", pd.__version__)
print("Numpy: ", np.__version__)

# hashing
hashing = lambda x : hashlib.sha256(x.encode()).hexdigest()


# import the cleaning data
pd.set_option("display.max_columns", 25)
df_cleaned = pd.read_csv("./processed/data_cleaned.csv")

df_cleaned.columns.tolist()

Pandas:  3.0.5
Numpy:  1.26.4

['Unnamed: 0',
 'Row ID',
 'Order ID',
 'Order Date',
 'Ship Date',
 'Ship Mode',
 'Customer ID',
 'Customer Name',
 'Segment',
 'Country',
 'City',
 'State',
 'Postal Code',
 'Region',
 'Product ID',
 'Category',
 'Sub-Category',
 'Product Name',
 'Sales',
 'Quantity',
 'Discount',
 'Profit',
 'Shipping Days',
 'Estimated Days',
 'Price',
 'Product Cost']

In [26]:

personal_columns = [
    'Customer Name',
    'Customer ID',
]

for col in personal_columns:
    if col in df_cleaned.columns:
        print(f"\n--- {col} ---")
        print(df_cleaned[col].head())
        print("Unique:", df_cleaned[col].nunique())
        print("Missing:", df_cleaned[col].isna().sum())

--- Customer Name ---
0        claire gute
1        claire gute
2    darrin huff van
3     o'donnell sean
4     o'donnell sean
Name: Customer Name, dtype: str
Unique: 793
Missing: 0

--- Customer ID ---
0    CG-12520
1    CG-12520
2    DV-13045
3    SO-20335
4    SO-20335
Name: Customer ID, dtype: str
Unique: 793
Missing: 0

In [27]:
# pseudonymize the Customer ID

df_cleaned['Customer ID Pseudo'] = df_cleaned['Customer ID'].astype(str).apply(hashing)

display(df_cleaned[['Customer ID', 'Customer ID Pseudo']].head())
# drop the Customer ID
df_cleaned = df_cleaned.drop(columns=['Customer ID'])
df_cleaned

  Customer ID                                 Customer ID Pseudo
0    CG-12520  860dcbde13f3d5792bd7ed41a7b6890ca3a75b65508bbc...
1    CG-12520  860dcbde13f3d5792bd7ed41a7b6890ca3a75b65508bbc...
2    DV-13045  3e049414e32502b60fdeca0439b42f7560263e8e88a224...
3    SO-20335  e82c08dc9dbace252fe1d9bc3e97034dc878e66f8ed297...
4    SO-20335  e82c08dc9dbace252fe1d9bc3e97034dc878e66f8ed297...

,Unnamed: 0,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer Name,Segment,Country,City,State,Postal Code,...,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit,Shipping Days,Estimated Days,Price,Product Cost,Customer ID Pseudo
0,0,1,CA-2016-152156,2016-11-08,2016-11-11,Second Class,claire gute,Consumer,United States,Henderson,Kentucky,42420.0,...,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600,2,0.00,41.9136,3,3.0,130.98,110.0232,860dcbde13f3d5792bd7ed41a7b6890ca3a75b65508bbc...
1,1,2,CA-2016-152156,2016-11-08,2016-11-11,Second Class,claire gute,Consumer,United States,Henderson,Kentucky,42420.0,...,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,3,0.00,219.5820,3,3.0,243.98,170.7860,860dcbde13f3d5792bd7ed41a7b6890ca3a75b65508bbc...
2,2,3,CA-2016-138688,2016-06-12,2016-06-16,Second Class,darrin huff van,Corporate,United States,Los Angeles,California,90036.0,...,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200,2,0.00,6.8714,4,3.0,7.31,3.8743,3e049414e32502b60fdeca0439b42f7560263e8e88a224...
3,3,4,US-2015-108966,2015-10-11,2015-10-18,Standard Class,o'donnell sean,Consumer,United States,Fort Lauderdale,Florida,33311.0,...,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,5,0.45,-383.0310,7,5.0,348.21,268.1217,e82c08dc9dbace252fe1d9bc3e97034dc878e66f8ed297...
4,4,5,US-2015-108966,2015-10-11,2015-10-18,Standard Class,o'donnell sean,Consumer,United States,Fort Lauderdale,Florida,33311.0,...,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680,2,0.20,2.5164,7,5.0,13.98,9.9258,e82c08dc9dbace252fe1d9bc3e97034dc878e66f8ed297...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9770,9989,9990,CA-2014-110422,2014-01-21,2014-01-23,Second Class,boeckenhauer tom,Consumer,United States,Miami,Florida,33180.0,...,Furniture,Furnishings,Ultra Door Pull Handle,25.2480,3,0.20,4.1028,2,3.0,10.52,7.0484,1334ff5fa71a2a4ad33e36c386055b9a40da9c770bdf87...
9771,9990,9991,CA-2017-121258,2017-02-26,2017-03-03,Standard Class,brooks dave,Consumer,United States,Costa Mesa,California,92627.0,...,Furniture,Furnishings,Tenex B1-RE Series Chair Mats for Low Pile Car...,91.9600,2,0.00,15.6332,5,5.0,45.98,38.1634,444a570c2489b0a9e5c99a1e26ee32ba5a372622918bb3...
9772,9991,9992,CA-2017-121258,2017-02-26,2017-03-03,Standard Class,brooks dave,Consumer,United States,Costa Mesa,California,92627.0,...,Technology,Phones,Aastra 57i VoIP phone,258.5760,2,0.20,19.3932,5,5.0,161.61,119.5914,444a570c2489b0a9e5c99a1e26ee32ba5a372622918bb3...
9773,9992,9993,CA-2017-121258,2017-02-26,2017-03-03,Standard Class,brooks dave,Consumer,United States,Costa Mesa,California,92627.0,...,Office Supplies,Paper,"It's Hot Message Books with Stickers, 2 3/4"" x 5""",29.6000,4,0.00,13.3200,5,5.0,7.40,4.0700,444a570c2489b0a9e5c99a1e26ee32ba5a372622918bb3...
9774,9993,9994,CA-2017-119914,2017-05-04,2017-05-09,Standard Class,chris cortes,Consumer,United States,Westminster,California,92683.0,...,Office Supplies,Appliances,"Acco 7-Outlet Masterpiece Power Center, Wihtou...",243.1600,2,0.00,72.9480,5,5.0,121.58,85.1060,f5010834e2f421f9d678d2386f4c8f9cece7cc72cc3b8f...

In [28]:
# pseudonymize the Customer Name

df_cleaned['Customer Name Pseudo'] = df_cleaned['Customer Name'].astype(str).apply(hashing)

display(df_cleaned[['Customer Name', 'Customer Name Pseudo']].head())
# drop the Customer Name
df_cleaned = df_cleaned.drop(columns=['Customer Name'])

     Customer Name                               Customer Name Pseudo
0      claire gute  9173dadf359b0cb7e29c9a654dab0904da9084fb419dbb...
1      claire gute  9173dadf359b0cb7e29c9a654dab0904da9084fb419dbb...
2  darrin huff van  5b4e754f05b1fa69137b2b54a28294cedb8447600d5ccb...
3   o'donnell sean  f5d6f90f48af7497ffe2d1368cea8edd968e7625433453...
4   o'donnell sean  f5d6f90f48af7497ffe2d1368cea8edd968e7625433453...